'use client';
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import Navbar from './components/Navbar';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <Head>
          {/* Move your metadata settings inside Head here */}
          <meta name="description" content="Generated by create next app" />
          <title>Create Next App</title>
        </Head>
        <body className={inter.className}>
          <div className='flex gap-0 justify-between items-center container py-10 text-white'>
            <Navbar />
            <div>
              <SignedOut>
                <SignInButton />
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </div>
          <main>{children}</main>
          {/* Uncomment this if you want to include a footer */}
          {/* <footer className="p-10 text-center bg-gray-800 mt-10 absolute bottom-0 w-full">
            Made With &hearts; By Mohammed Zaheer
          </footer> */}
        </body>
      </html>
    </ClerkProvider>
  );
}