import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs';
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
          <meta name="description" content={metadata.description} />
          <title>{metadata.title}</title>
        </head>
        <body className={inter.className}>
          <div className='flex gap-0 justify-between items-center container py-10 text-white'>
            <Navbar/>
            <div>
              <SignedOut>
                <SignInButton />
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </div>
          <main>
            {children}
          </main>
          {/* Uncomment this if you want to include a footer */}
          {/* <footer className="p-10 text-center bg-gray-800 mt-10 absolute bottom-0 w-[100%]">
            Made With &hearts; By Mohammed Zaheer
          </footer> */}
        </body>
      </html>
    </ClerkProvider>
  );
}








// import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs';
// import { Inter } from 'next/font/google';
// import Navbar from './components/Navbar';
// import './globals.css';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({ children }) {
//   return (
//     <ClerkProvider>
//       <html lang="en" suppressHydrationWarning>
//         <head />
//         <body>
//           <div className='flex gap-0 justify-between items-center container py-10 text-white'>
//             <Navbar/>
//             <div>
//               <SignedOut>
//                 <SignInButton />
//               </SignedOut>
//               <SignedIn>
//                 <UserButton />
//               </SignedIn>
//             </div>
//           </div>
//           {children}
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }
